### ISSUE TITLE
Malos proto files

### ISSUE THREAD

**Issue by jaumard** [matrix-io/protocol-buffers#56]
Would be nice to have an npm package with the proto file of malos. Like this we can get them really easily on our node application and can also maintain them.

Thanks :)

**Comment by maciekrb** [comment]
Hi @jaumard, 

We just published `matrix-protos` npm package containing protocol buffers. You can see a usage example in this PR: https://github.com/matrix-io/matrix-malos-wakeword/pull/9/files

Cheers !

**Comment by jaumard** [comment]
Hi @maciekrb ! 

Thanks for this ! A small README on the npm page with basic usage would be nice in the future.
I integrate `matrix-protos`, works great thanks ! Cool things to not have to use protobuff ourself ^^ 👍 

Cheers

**Comment by maciekrb** [comment]
@jaumard still an early PR but should work. Let me know what you think: https://github.com/matrix-io/protocol-buffers/tree/mr/moduledoc/nodejs

**Comment by jaumard** [comment]
Look like pretty complete ! Very nice ! :D 👍 maybe an example with microphones would be a nice addition.
